package com.gephub.builder_service.service;

import org.eclipse.jgit.api.Git;
import org.eclipse.jgit.transport.CredentialsProvider;
import org.eclipse.jgit.transport.UsernamePasswordCredentialsProvider;
import org.kohsuke.github.GHRepository;
import org.kohsuke.github.GitHub;
import org.kohsuke.github.GitHubBuilder;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Map;
import java.util.zip.ZipInputStream;
import java.util.zip.ZipEntry;
import java.io.ByteArrayInputStream;

@Service
public class GitHubService {
    private final String accessToken;
    private final String storageRoot;

    public GitHubService(@Value("${gephub.builder.github.accessToken:}") String accessToken,
                        @Value("${gephub.builder.storage.root}") String storageRoot) {
        this.accessToken = accessToken;
        this.storageRoot = storageRoot;
    }

    public Map<String, String> createRepository(String name, boolean isPrivate) throws IOException {
        if (accessToken == null || accessToken.isBlank()) {
            return Map.of("name", name, "url", "https://github.com/placeholder/" + name, "cloneUrl", "https://github.com/placeholder/" + name + ".git");
        }
        GitHub github = new GitHubBuilder().withOAuthToken(accessToken).build();
        GHRepository repo = github.createRepository(name)
                .private_(isPrivate)
                .description("Generated by Gephub Builder")
                .create();
        return Map.of(
                "name", repo.getName(),
                "url", repo.getHtmlUrl().toString(),
                "cloneUrl", repo.getGitTransportUrl()
        );
    }

    public void pushCode(String repoName, byte[] zipContent, String cloneUrl) throws Exception {
        if (accessToken == null || accessToken.isBlank()) {
            throw new IllegalStateException("GitHub access token not configured");
        }
        
        // Create temporary directory for extraction
        Path tempDir = Files.createTempDirectory("builder-" + repoName);
        try {
            // Extract ZIP
            extractZip(zipContent, tempDir);
            
            // Initialize git repo
            Git git = Git.init().setDirectory(tempDir.toFile()).call();
            git.add().addFilepattern(".").call();
            git.commit().setMessage("Initial commit from Gephub Builder").call();
            
            // Configure remote and push
            CredentialsProvider creds = new UsernamePasswordCredentialsProvider(accessToken, "");
            git.remoteAdd()
                    .setName("origin")
                    .setUri(org.eclipse.jgit.transport.URIish.create(cloneUrl))
                    .call();
            git.push()
                    .setCredentialsProvider(creds)
                    .setRemote("origin")
                    .setRefSpecs(org.eclipse.jgit.transport.RefSpec.SPECIAL_PUSH_HEAD)
                    .call();
        } finally {
            // Cleanup
            deleteDirectory(tempDir.toFile());
        }
    }

    private void extractZip(byte[] zipContent, Path targetDir) throws IOException {
        try (ZipInputStream zis = new ZipInputStream(new ByteArrayInputStream(zipContent))) {
            ZipEntry entry;
            while ((entry = zis.getNextEntry()) != null) {
                Path filePath = targetDir.resolve(entry.getName());
                if (entry.isDirectory()) {
                    Files.createDirectories(filePath);
                } else {
                    Files.createDirectories(filePath.getParent());
                    Files.copy(zis, filePath);
                }
                zis.closeEntry();
            }
        }
    }

    private void deleteDirectory(File directory) {
        if (directory.exists()) {
            File[] files = directory.listFiles();
            if (files != null) {
                for (File file : files) {
                    if (file.isDirectory()) {
                        deleteDirectory(file);
                    } else {
                        file.delete();
                    }
                }
            }
            directory.delete();
        }
    }

    public String getRepositoryUrl(String repoName) {
        return "https://github.com/" + repoName;
    }
}

